# Generated by Django 2.2.12 on 2020-07-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeshift', models.TimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
