# Generated by Django 2.2.14 on 2020-07-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSite',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sibparser.Site')),
                ('title', models.CharField(max_length=200)),
                ('encoding', models.CharField(max_length=200)),
                ('h1', models.CharField(max_length=200)),
            ],
        ),
    ]
