# Generated by Django 2.2.12 on 2020-07-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibparser', '0002_parsedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedsite',
            name='successfully',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parsedsite',
            name='encoding',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='parsedsite',
            name='site',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sibparser.Site'),
        ),
        migrations.AlterField(
            model_name='parsedsite',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
