# Generated by Django 2.2.12 on 2020-07-09 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibparser', '0004_auto_20200709_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedsite',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sibparser.Site'),
        ),
    ]
