# Generated by Django 2.2.12 on 2020-07-09 07:28

from django.db import migrations, models
import sibparser.models


class Migration(migrations.Migration):

    dependencies = [
        ('sibparser', '0008_auto_20200709_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='timeshiftSeconds',
            field=models.IntegerField(default=0, validators=[sibparser.models.validatorNegative]),
        ),
    ]
